In [1]:
import numpy as np
import cv2

In [ ]:
img = cv2.imread('dp.jpg' , cv2.IMREAD_COLOR)
#Each frame, like an image, then breaks down into pixels stored in rows and columns within the frame/picture. 
#Each pixel has a coordinate location, and each pixel is comprised of color values.

#Refrencing a specific pixel
px = img[55 , 55] #will give the color value of the pixel on (55 ,55) location
print(px)

#We can further modify the pixel
img[55 ,55] = [255 , 255 , 255]
print(px)

# refrencing ROI or Region of Image (It is basically a sub image or a part of the image)
roi = img[100:150 , 100:150]
print(roi)
img[100:150 , 100:150] = [255 , 255, 255]
print(roi)


#Take an roi and move to another place, like copy and paste
part_pic = img[37 : 111 , 107:194]
img[0:74 , 0:87] = part_pic
#We are taking the same area of the image as the area of part_pic(it is imp otherwise copy paste will not happen) and pasting part_pic 

cv2.imshow('image' , img)
cv2.waitKey(0)
cv2.destroyAllWindows()
for i in range(5):
    cv2.waitKey(1)



[235 235 235]
[255 255 255]
[[[239 239 239]
  [240 240 240]
  [240 240 240]
  ..., 
  [210 210 210]
  [212 212 212]
  [219 219 219]]

 [[239 239 239]
  [240 240 240]
  [241 241 241]
  ..., 
  [212 212 212]
  [219 219 219]
  [226 226 226]]

 [[239 239 239]
  [240 240 240]
  [241 241 241]
  ..., 
  [215 215 215]
  [226 226 226]
  [232 232 232]]

 ..., 
 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ..., 
  [231 231 231]
  [234 234 234]
  [236 236 236]]

 [[238 238 238]
  [239 239 239]
  [240 240 240]
  ..., 
  [235 235 235]
  [236 236 236]
  [237 237 237]]

 [[238 238 238]
  [239 239 239]
  [241 241 241]
  ..., 
  [235 235 235]
  [236 236 236]
  [236 236 236]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[2